{% set version = "0.5.6" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-survmisc
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/survMisc_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/survMisc/survMisc_{{ version }}.tar.gz
  sha256: d911125bc374dfc67f31a81ebeaf98a09cac8f81e30259655ab136ebf4718c04

build:
  noarch: generic
  merge_build_host: true  # [win]
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-kmsurv
    - r-data.table
    - r-ggplot2
    - r-gridextra
    - r-km.ci
    - r-knitr
    - r-survival
    - r-xtable
    - r-zoo
  run:
    - r-base
    - r-kmsurv
    - r-data.table
    - r-ggplot2
    - r-gridextra
    - r-km.ci
    - r-knitr
    - r-survival
    - r-xtable
    - r-zoo

test:
  commands:
    - $R -e "library('survMisc')"           # [not win]
    - "\"%R%\" -e \"library('survMisc')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=survMisc
  license: GPL-2.0-only
  summary: A collection of functions to help in the analysis of right-censored survival data. These extend the methods available in package:survival.
  license_family: GPL2
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
