travis:
  secure:
    BINSTAR_TOKEN: qeW34hZTwCjBCTLqfMohfp67fXbZy0X02k2GGqa/wPrtxKwD7QQcSxR/MfyF06DleTnbU99EuuBbC/aLZ0hWxF2ypBpthlij1KEmjmPjqdxjulBPLpggPA5vcMrQ3MsWyVC6JQAXS5yAyrjNWlbCiYcI2xZ/80Ez5ntgzAVtBaMpw0r4PDuq1OY2XvxECXv+0W/7I6+ZgokpX0r9TmGRNItk4tG/cQlkNbFCl8mCdG7wWaq3KhDrvbBy5D635e5sIHMbxOR6NBHb5F59o45UMWrxw6yzFf0Xgf+maf8clgY25Ky/n9oJYRNBmQoVLNnq/6Otubxn2G9Slk5peHi/FsfAkB8qAlNPJbUYJTZSjaCnVvtbOlbse3id8SkoFN3lDZmiARTkG+sHlgZnY1d4XA08NEa4XRCi4YSBuks5f96eYTwxsno7IPjX/k85I9xD2Okpw4i064joKrdVEjT2EXJYthJvL+24S4xr9x2AYtkhUVklfTqFRx4rJ2jIKBCHKobz+/W1hL70gAV9c0W4+Fgija8OmhA9zP1QZesEhkMiEsQdBqTMVwRXaE67VBSGobUueVQiHhrrJP2cc5+XDK2/VTDLXzfxK0BgA05DikcUOLRvACKJTB0WbyFAVcmkpFg4kZAxj5xmz0COFFhgbAKJPcwFKHEMBm99pB7MHMY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
