appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Rma1BSwoRd0vfRAFOKg60lRYaimvYoxPP+sirEl9M0v7S5gKl44dRAE0JsvfaQUODnUQYQ0B6wQSztb07n2eC/NpOfct1XK0AzbAPjgLebf1oVGj4bmV75PoENCy8eS3lBKRwo66PJmupw1lc7KIaxHka7X6paByVMxo4kRmjVAByPR9aH5ZiSlyZETjhxqkXRjIWzNcN55RlaRMUQvBj79wgCMAXm3CjusvVcs64JSigF6B3l8pEQ4C3L3A7U8ebBx0ew6wecVbkdeaLRD0dw0vVOPpuIg9R5eaqViTXz9DS1CEUUsLLfUf+TlpOUC43tO+a3I/nunCSCWDXChgiCtgWDyTIzJ6Ff8C8A1ibX+BGbVzhJ5OWy2lrutCyyJuicCCZK5PGaAz4Pa+G6Pawo3GbjA1i5GFtaERg+wb6TzECE1N7Bj6PCOlOpDhr9GPfnVm/oSLrywo1wzaJH+7hzpeNI5ovcKa1hq7UbNoPpBYH9eh2m52/Q2gkbnemlywZupaNxjoxWrZMTdYB7TDVIBvvlbjcnhC66sgk0xHY33hodN5bEU/37qw6Ew1jP8MTfVeU+Re7Cl5Cr4Ra/tuvs/dORNo1bkgfrR5e3Qwco7OSK4hq8jQ6UD/lRkoV+gvwY2kKufBSwXTxos1IWtbUIHuplHXYLTuecmrNJRAdXs=}
